# Generated by Django 2.2.12 on 2020-04-25 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=50, verbose_name='高校名称')),
                ('school_url', models.CharField(max_length=100, verbose_name='高校URL地址')),
                ('is_build', models.BooleanField(default=False, verbose_name='是否已经建立词库')),
                ('area', models.CharField(max_length=100, verbose_name='所属地区')),
            ],
            options={
                'verbose_name_plural': '高校信息',
                'verbose_name': '高校信息',
            },
        ),
        migrations.CreateModel(
            name='WordToCnt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=100, verbose_name='单词')),
                ('cnt_list', models.TextField(verbose_name='网页列表')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchcenter.SchoolInfo', verbose_name='学校')),
            ],
            options={
                'verbose_name_plural': '单词和网页',
                'verbose_name': '单词和网页',
            },
        ),
        migrations.CreateModel(
            name='CntToUrl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cnt', models.IntegerField(verbose_name='子网页序号')),
                ('url', models.CharField(max_length=50, verbose_name='子网页URL')),
                ('title', models.CharField(max_length=200, verbose_name='子网页标题')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchcenter.SchoolInfo', verbose_name='学校')),
            ],
            options={
                'verbose_name_plural': '网页序号和URL',
                'verbose_name': '网页序号和URL',
            },
        ),
    ]
