# Generated by Django 2.2.12 on 2020-05-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchcenter', '0005_searchhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, verbose_name='分类')),
                ('category_list', models.CharField(max_length=200, verbose_name='搜索字段')),
            ],
        ),
    ]
