# Generated by Django 2.2.12 on 2020-05-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchcenter', '0006_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类检索', 'verbose_name_plural': '分类检索'},
        ),
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'verbose_name': '历史记录', 'verbose_name_plural': '历史记录'},
        ),
        migrations.AlterModelOptions(
            name='searchresult',
            options={'verbose_name': '搜索结果', 'verbose_name_plural': '搜索结果'},
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='tf_idf',
            field=models.FloatField(verbose_name='TF-IDF'),
        ),
    ]
