# Generated by Django 2.2.12 on 2020-04-23 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=50, verbose_name='分类标签')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '分类标签',
                'verbose_name': '分类标签',
            },
        ),
        migrations.CreateModel(
            name='ArticleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Ancientear', max_length=50, verbose_name='作者')),
                ('title', models.CharField(default='暂无标题', max_length=200, verbose_name='文章标题')),
                ('content', tinymce.models.HTMLField(default='暂无内容', verbose_name='文章内容')),
                ('articlephoto', models.ImageField(blank=True, upload_to='images/article/', verbose_name='文章图片')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('article_tag', models.ManyToManyField(blank=True, to='usercenter.ArticleTag', verbose_name='文章标签')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '动态内容',
                'verbose_name': '动态内容',
            },
        ),
    ]
