# Generated by Django 2.2.12 on 2020-04-23 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleinfo',
            name='article_tag',
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='article_tag',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='usercenter.ArticleTag', verbose_name='文章标签'),
            preserve_default=False,
        ),
    ]
