# Generated by Django 2.2.12 on 2020-04-23 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0002_auto_20200423_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='abstract',
            field=models.TextField(default='暂无摘要', verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='article_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercenter.ArticleTag', verbose_name='分类标签'),
        ),
    ]
