# Generated by Django 2.2.12 on 2020-04-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0003_auto_20200423_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_name', models.CharField(default='暂无名称', max_length=50, verbose_name='图片名称')),
                ('category', models.CharField(max_length=10, verbose_name='图片分类')),
                ('image', models.ImageField(blank=True, upload_to='images/collection/', verbose_name='图片')),
                ('description', models.CharField(default='暂无描述', max_length=200, verbose_name='图片描述')),
            ],
            options={
                'verbose_name_plural': '图片收藏',
                'verbose_name': '图片收藏',
            },
        ),
    ]
