# Generated by Django 2.2.12 on 2020-04-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='匿名用户', max_length=50, verbose_name='姓名')),
                ('email', models.EmailField(default='暂无信息', max_length=50, verbose_name='邮箱')),
                ('type', models.CharField(default='暂无信息', max_length=50, verbose_name='意见类型')),
                ('info', models.TextField(default='暂无信息', verbose_name='反馈信息')),
            ],
        ),
    ]
