# Generated by Django 2.2.12 on 2020-04-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_feedbackinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackinfo',
            options={'verbose_name': '反馈信息', 'verbose_name_plural': '反馈信息'},
        ),
        migrations.AlterField(
            model_name='feedbackinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
