# Generated by Django 2.2.12 on 2020-04-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200420_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/user/', verbose_name='头像'),
        ),
    ]
