# Generated by Django 2.2.12 on 2020-05-03 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200424_0921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': '用户列表', 'verbose_name_plural': '用户列表'},
        ),
    ]
